# Generated by Django 3.0.5 on 2021-04-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210417_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageid',
            new_name='name',
        ),
    ]
