# Generated by Django 3.0.5 on 2021-05-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210417_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFarmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataNum', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('outTemp', models.FloatField()),
                ('inTemp', models.FloatField()),
                ('outHumidity', models.FloatField()),
                ('inHumidity', models.FloatField()),
                ('co2ppm', models.FloatField()),
                ('src', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
