# Generated by Django 3.0.5 on 2021-05-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210502_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartfarmdata',
            options={'ordering': ['id']},
        ),
    ]
